services:
  caddy:
    image: caddy:2.11.3-builder-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      - internal

  prometheus:
    image: prom/prometheus:v3.12.0-rc.0-distroless
    restart: unless-stopped
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - internal

volumes:
  caddy_data:      # ~/.local/share/docker/volumes/backend_caddy_data
  caddy_config:    # ~/.local/share/docker/volumes/backend_caddy_config
  prometheus_data: # ~/.local/share/docker/volumes/backend_prometheus_data

networks:
  internal:
    driver: bridge