services:
  caddy:
    image: caddy:2.11.3-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ${HOST_WORKSPACE}/caddy/Caddyfile:/etc/caddy/Caddyfile:rw
    networks:
      - internal

  prometheus:
    image: prom/prometheus:v3.12.0-rc.0-distroless
    restart: unless-stopped
    volumes:
      - prometheus_data:/prometheus
      - ${HOST_WORKSPACE}/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - internal

volumes:
  caddy_data:
  caddy_config:
  prometheus_data:

networks:
  internal:
    driver: bridge
